# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 610c765c8c22432fdc674f82f3c5fab5174c253c77a2d8864601fb345057855465b5942f1756fb5d7ddf60050879caa13f46ecdbb39921ecd6502822870b4807

test:
  secret_key_base: c74385ecb53d33a610516ac20704c0ede7eba20458cf45ac32125f0c137d94b37c5406e918458fc6a70ed45433ac0a515c1a1151c3a6b3ee61947d4b8c18af20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
